"""Command-oriented binding catalog.

Transcribed from `docs/reference/binary/effdir.md` ("Parser cross-reference"
section) per the schema in `docs/reference/binary/effdir-editor-spec.md`
("Command-oriented interpretation"). This is a starter set, not the full
table: see the spec for why a partial catalog is intentional.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Literal, Optional

Role = Literal["parser", "reader", "writer", "consumer"]
Evidence = Literal["wire", "parser", "runtime", "inferred"]
Encoding = Literal[
    "u8", "u16", "u32", "f32", "Vec2", "Vec3",
    "range", "enum", "curve", "resource_key", "string", "raw",
]

EFFDIR_MD = "docs/reference/binary/effdir.md"


@dataclass(frozen=True)
class DocumentRef:
    path: str
    anchor: Optional[str] = None


@dataclass(frozen=True)
class BitRef:
    member_path: str
    bit: int


@dataclass(frozen=True)
class CodeRef:
    address: str
    role: Role


@dataclass(frozen=True)
class Transform:
    description: str
    reversible: bool
    implementation: str


@dataclass(frozen=True)
class CommandBinding:
    id: str
    command_path: str
    syntax_sources: List[DocumentRef]
    record_type: str
    member_paths: List[str]
    presence_bits: List[BitRef]
    encoding: str
    transforms: List[Transform]
    shared_storage_group: Optional[str]
    conflicts: List[str]
    evidence: str
    parser_refs: List[CodeRef]
    runtime_refs: List[CodeRef]
    notes: str


def _doc(anchor: Optional[str] = None) -> List[DocumentRef]:
    return [DocumentRef(path=EFFDIR_MD, anchor=anchor)]


CATALOG: List[CommandBinding] = [
    CommandBinding(
        id="particle.life",
        command_path="life",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["life"],
        presence_bits=[],
        encoding="range",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0077E104", role="parser")],
        runtime_refs=[],
        notes="+0x0c/+0x10, life minimum/maximum, cParticleLifeCommand::Parse",
    ),
    CommandBinding(
        id="particle.preroll",
        command_path="preroll",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["preroll"],
        presence_bits=[],
        encoding="f32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0077E104", role="parser")],
        runtime_refs=[],
        notes="+0x1c, preroll, cParticleLifeCommand::Parse",
    ),
    CommandBinding(
        id="particle.emit",
        command_path="emit",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["emit_curve"],
        presence_bits=[BitRef(member_path="leading_bitset", bit=1)],
        encoding="curve",
        transforms=[],
        shared_storage_group="particle.emit_curve@+0x088",
        conflicts=["particle.maintain", "particle.inject"],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078667C", role="parser")],
        runtime_refs=[],
        notes="+0x88 vector, emit rate value; shared storage with maintain/inject",
    ),
    CommandBinding(
        id="particle.maintain",
        command_path="maintain",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["emit_curve"],
        presence_bits=[BitRef(member_path="leading_bitset", bit=2)],
        encoding="curve",
        transforms=[],
        shared_storage_group="particle.emit_curve@+0x088",
        conflicts=["particle.emit", "particle.inject"],
        evidence="parser",
        parser_refs=[CodeRef(address="0x00785E28", role="parser")],
        runtime_refs=[],
        notes="+0x88 vector, maintain value; shared storage with emit/inject",
    ),
    CommandBinding(
        id="particle.inject",
        command_path="inject",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["emit_curve"],
        presence_bits=[BitRef(member_path="leading_bitset", bit=3)],
        encoding="curve",
        transforms=[],
        shared_storage_group="particle.emit_curve@+0x088",
        conflicts=["particle.emit", "particle.maintain"],
        evidence="parser",
        parser_refs=[CodeRef(address="0x00785F28", role="parser")],
        runtime_refs=[],
        notes="+0x88 vector, inject value; shared storage with emit/maintain",
    ),
    CommandBinding(
        id="particle.collision.effect",
        command_path="collision.effect",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["collision_effect_or_death"],
        presence_bits=[BitRef(member_path="leading_bitset", bit=8)],
        encoding="f32",
        transforms=[],
        shared_storage_group="particle.collision_effect_or_death@+0x150",
        conflicts=["particle.collision.death"],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078A790", role="parser")],
        runtime_refs=[],
        notes="+0x150, collision effect/death shared scalar; do not expose as two independent values",
    ),
    CommandBinding(
        id="particle.collision.death",
        command_path="collision.death",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["collision_effect_or_death"],
        presence_bits=[BitRef(member_path="leading_bitset", bit=8)],
        encoding="f32",
        transforms=[
            Transform(
                description="parser clamps death through [0,1]",
                reversible=False,
                implementation="clamp",
            )
        ],
        shared_storage_group="particle.collision_effect_or_death@+0x150",
        conflicts=["particle.collision.effect"],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078A790", role="parser")],
        runtime_refs=[],
        notes="+0x150, collision effect/death shared scalar; parser clamps death and deathByWater through [0,1]",
    ),
    CommandBinding(
        id="particle.randomWalk.delay",
        command_path="randomWalk.delay",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["random_walk_delay"],
        presence_bits=[BitRef(member_path="leading_bitset", bit=23)],
        encoding="range",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0077FC62", role="parser")],
        runtime_refs=[],
        notes="+0x16c/+0x170, random-walk delay minimum/maximum",
    ),
    CommandBinding(
        id="particle.randomWalk.strength",
        command_path="randomWalk.strength",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["random_walk_strength"],
        presence_bits=[BitRef(member_path="leading_bitset", bit=23)],
        encoding="range",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0077FC62", role="parser")],
        runtime_refs=[],
        notes="+0x174/+0x178, random-walk strength minimum/maximum",
    ),
    CommandBinding(
        id="particle.randomWalk.turn",
        command_path="randomWalk.turn",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["random_walk_turn"],
        presence_bits=[BitRef(member_path="leading_bitset", bit=23)],
        encoding="range",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0077FC62", role="parser")],
        runtime_refs=[],
        notes="+0x17c/+0x180, random-walk turn minimum/maximum",
    ),
    CommandBinding(
        id="particle.randomWalk.preferDir",
        command_path="randomWalk.preferDir",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["prefer_direction"],
        presence_bits=[
            BitRef(member_path="leading_bitset", bit=24),
            BitRef(member_path="leading_bitset", bit=25),
        ],
        encoding="Vec3",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0077FC62", role="parser")],
        runtime_refs=[],
        notes="+0x184, random-walk preferDir; bits 23-25 = present/wait/preferSea",
    ),
    CommandBinding(
        id="particle.model.drawOption",
        command_path="model",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["draw_mode"],
        presence_bits=[],
        encoding="u8",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078AC9E", role="parser")],
        runtime_refs=[],
        notes="+0xd4, model draw-option byte; parser writes 3; enum domain is NOT established, keep as u8 not enum",
    ),
    CommandBinding(
        id="particle.model.resourceKey",
        command_path="model",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["resource_key"],
        presence_bits=[BitRef(member_path="third_bitset", bit=0)],
        encoding="resource_key",
        transforms=[],
        shared_storage_group="particle.resource_key@+0x0d0",
        conflicts=["particle.texture"],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078AC9E", role="parser")],
        runtime_refs=[],
        notes="+0xd0, model resource key; texture and model commands share this storage",
    ),
    CommandBinding(
        id="particle.texture",
        command_path="texture",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["resource_key"],
        presence_bits=[],
        encoding="resource_key",
        transforms=[],
        shared_storage_group="particle.resource_key@+0x0d0",
        conflicts=["particle.model.resourceKey"],
        evidence="parser",
        parser_refs=[CodeRef(address="0x00785C30", role="parser")],
        runtime_refs=[],
        notes="+0xd0, texture resource key; shared storage with model command",
    ),
    CommandBinding(
        id="particle.size.vary",
        command_path="size.vary",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["size_vary"],
        presence_bits=[],
        encoding="f32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x00786304", role="parser")],
        runtime_refs=[],
        notes="+0x68, size vary value, cParticleSizeCommand::Parse",
    ),
    CommandBinding(
        id="particle.size.curve",
        command_path="size",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["size_curve"],
        presence_bits=[],
        encoding="curve",
        transforms=[
            Transform(
                description="parser multiplies size-curve inputs by 50 before storing",
                reversible=True,
                implementation="scale_by(50)",
            )
        ],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x00786304", role="parser")],
        runtime_refs=[],
        notes="+0xac vector, size-over-time; x50 is a parser-unit transform, not proof of engine semantic unit",
    ),
    CommandBinding(
        id="particle.aspect.vary",
        command_path="aspect.vary",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["aspect_vary"],
        presence_bits=[],
        encoding="f32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x00786416", role="parser")],
        runtime_refs=[],
        notes="+0x6c, aspect vary value, cParticleAspectCommand::Parse",
    ),
    CommandBinding(
        id="particle.rotate.vary",
        command_path="rotate.vary",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["rotate_vary"],
        presence_bits=[],
        encoding="f32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x00786516", role="parser")],
        runtime_refs=[],
        notes="+0x70, rotate vary value, cParticleRotateCommand::Parse",
    ),
    CommandBinding(
        id="particle.rotate.offset",
        command_path="rotate.offset",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["rotate_offset"],
        presence_bits=[],
        encoding="f32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x00786516", role="parser")],
        runtime_refs=[],
        notes="+0x74, rotate offset value, cParticleRotateCommand::Parse",
    ),
    CommandBinding(
        id="particle.alpha.vary",
        command_path="alpha.vary",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["alpha_vary"],
        presence_bits=[],
        encoding="f32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078A3BC", role="parser")],
        runtime_refs=[],
        notes="+0x78, alpha vary value, cParticleAlphaCommand::Parse",
    ),
    CommandBinding(
        id="particle.color.curve",
        command_path="color",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["color_curve"],
        presence_bits=[],
        encoding="curve",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078A538", role="parser")],
        runtime_refs=[],
        notes="+0x94 vector, color curve values, cParticleColorCommand::Parse",
    ),
    CommandBinding(
        id="particle.terrainRepel",
        command_path="terrainRepel",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["terrain_repel", "scout", "vertical", "kill_height"],
        presence_bits=[BitRef(member_path="leading_bitset", bit=10)],
        encoding="Vec2",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0077FFD4", role="parser")],
        runtime_refs=[],
        notes="+0x13c/+0x140 first two values, +0x144 scout, +0x148 vertical, +0x14c killHeight",
    ),
    CommandBinding(
        id="particle.force",
        command_path="force",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["force"],
        presence_bits=[],
        encoding="Vec3",
        transforms=[],
        shared_storage_group=None,
        conflicts=["particle.wind"],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078710C", role="parser")],
        runtime_refs=[],
        notes="+0xe0 vector, accumulated gravity/wind force, cParticleForceCommand::Parse",
    ),
    CommandBinding(
        id="particle.globalWind",
        command_path="global_wind",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["global_wind"],
        presence_bits=[],
        encoding="f32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078710C", role="parser")],
        runtime_refs=[],
        notes="+0xec, global_wind, cParticleForceCommand::Parse",
    ),
    CommandBinding(
        id="particle.bomb",
        command_path="bomb",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["bomb", "bomb_direction"],
        presence_bits=[],
        encoding="f32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078710C", role="parser")],
        runtime_refs=[],
        notes="+0xf0 scalar, +0xf4 vector direction, cParticleForceCommand::Parse",
    ),
    CommandBinding(
        id="particle.wiggle",
        command_path="wiggle",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["wiggles"],
        presence_bits=[BitRef(member_path="third_bitset", bit=8)],
        encoding="curve",
        transforms=[],
        shared_storage_group="particle.wiggle_mode@third_bitset.8",
        conflicts=["particle.wiggleVerts", "particle.uv", "particle.alpha_warp"],
        evidence="parser",
        parser_refs=[CodeRef(address="0x007880EC", role="parser")],
        runtime_refs=[],
        notes="+0x108 vector, wiggle/wiggleDir records, cParticleWarpCommand::Parse; third bitset bit 8 is a shared mode bit",
    ),
    CommandBinding(
        id="particle.uv",
        command_path="uv",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["uv_scale", "uv_range"],
        presence_bits=[BitRef(member_path="third_bitset", bit=8)],
        encoding="f32",
        transforms=[],
        shared_storage_group="particle.wiggle_mode@third_bitset.8",
        conflicts=["particle.wiggle", "particle.wiggleVerts"],
        evidence="parser",
        parser_refs=[CodeRef(address="0x007880EC", role="parser")],
        runtime_refs=[],
        notes="+0x114 scalar, +0x118 vector, cParticleWarpCommand::Parse",
    ),
    CommandBinding(
        id="particle.source",
        command_path="source",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["source_bounds"],
        presence_bits=[],
        encoding="raw",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0077F0D6", role="parser")],
        runtime_refs=[],
        notes="+0x50 bounding box, particle source region, cParticleSourceCommand::Parse; point/square/quad/cube/box/dice forms share this storage",
    ),
    CommandBinding(
        id="particle.emit.delay",
        command_path="emit.delay",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["emit_curve"],
        presence_bits=[],
        encoding="range",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078667C", role="parser")],
        runtime_refs=[],
        notes="+0x20/+0x24, emission delay range, cParticleEmitCommand::Parse",
    ),
    CommandBinding(
        id="particle.alignment",
        command_path="alignment",
        syntax_sources=_doc("particle-records-direct-command-assignments"),
        record_type="ParticleDescriptor",
        member_paths=["alignment_mode", "alignment_damp", "bank_range"],
        presence_bits=[BitRef(member_path="third_bitset", bit=7)],
        encoding="enum",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078AA74", role="parser")],
        runtime_refs=[],
        notes="+0xd5 alignment enum, +0x190 damp, +0x194/+0x198 bank/windBank range, cParticleAlignmentCommand::Parse",
    ),
    CommandBinding(
        id="decal.draw",
        command_path="draw",
        syntax_sources=_doc("decal-descriptor"),
        record_type="DecalDescriptor",
        member_paths=["draw_mode"],
        presence_bits=[],
        encoding="enum",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x00785890", role="parser")],
        runtime_refs=[],
        notes="+0x08, draw enum; enum values are not complete yet",
    ),
    CommandBinding(
        id="decal.texture",
        command_path="texture",
        syntax_sources=_doc("decal-descriptor"),
        record_type="DecalDescriptor",
        member_paths=["texture_key", "texture_offset", "texture_repeat"],
        presence_bits=[
            BitRef(member_path="flags", bit=1),
            BitRef(member_path="flags", bit=2),
            BitRef(member_path="flags", bit=3),
            BitRef(member_path="flags", bit=5),
        ],
        encoding="resource_key",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x00785890", role="parser")],
        runtime_refs=[],
        notes="+0x04 texture key, +0x5c offset vector, +0x58 repeat; bits 1/2/3/5 = light/water/repeat/ring",
    ),
    CommandBinding(
        id="decal.life",
        command_path="life",
        syntax_sources=_doc("decal-descriptor"),
        record_type="DecalDescriptor",
        member_paths=["life"],
        presence_bits=[BitRef(member_path="flags", bit=6)],
        encoding="f32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078017C", role="parser")],
        runtime_refs=[],
        notes="+0x0c, life value; +0x00 bit 6 = static; +0x09 mode static/loop/single/sustain = 1/1/2/3",
    ),
    CommandBinding(
        id="decal.rotate",
        command_path="rotate",
        syntax_sources=_doc("decal-descriptor"),
        record_type="DecalDescriptor",
        member_paths=["rotation", "rotate_vary"],
        presence_bits=[],
        encoding="curve",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x007889A0", role="parser")],
        runtime_refs=[],
        notes="+0x10 vector rotate curve, +0x54 rotate vary, cDecalRotateCommand::Parse",
    ),
    CommandBinding(
        id="decal.size",
        command_path="size",
        syntax_sources=_doc("decal-descriptor"),
        record_type="DecalDescriptor",
        member_paths=["size", "size_vary"],
        presence_bits=[BitRef(member_path="flags", bit=4)],
        encoding="curve",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x007887CC", role="parser")],
        runtime_refs=[],
        notes="+0x1c vector size curve, +0x50 size vary, +0x00 bit 4 = cityScale, cDecalSizeCommand::Parse",
    ),
    CommandBinding(
        id="decal.alpha",
        command_path="alpha",
        syntax_sources=_doc("decal-descriptor"),
        record_type="DecalDescriptor",
        member_paths=["alpha", "alpha_vary"],
        presence_bits=[],
        encoding="curve",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078977C", role="parser")],
        runtime_refs=[],
        notes="+0x28 vector alpha curve, +0x4c alpha vary, cDecalAlphaCommand::Parse",
    ),
    CommandBinding(
        id="decal.color",
        command_path="color",
        syntax_sources=_doc("decal-descriptor"),
        record_type="DecalDescriptor",
        member_paths=["color"],
        presence_bits=[],
        encoding="curve",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x007898F8", role="parser")],
        runtime_refs=[],
        notes="+0x34 vector color curve, cDecalColorCommand::Parse",
    ),
    CommandBinding(
        id="decal.aspect",
        command_path="aspect",
        syntax_sources=_doc("decal-descriptor"),
        record_type="DecalDescriptor",
        member_paths=["aspect"],
        presence_bits=[],
        encoding="curve",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x00788910", role="parser")],
        runtime_refs=[],
        notes="+0x40 vector aspect curve, cDecalAspectCommand::Parse",
    ),
    CommandBinding(
        id="shake.length",
        command_path="length",
        syntax_sources=_doc("shake-descriptor"),
        record_type="ShakeDescriptor",
        member_paths=["length", "fade"],
        presence_bits=[],
        encoding="f32",
        transforms=[
            Transform(
                description="parser clamps fade to length when a larger fade is supplied",
                reversible=False,
                implementation="clamp(fade, max=length)",
            )
        ],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0077DF20", role="parser")],
        runtime_refs=[],
        notes="+0x00 length, +0x04 fade, cShakeLengthCommand::Parse",
    ),
    CommandBinding(
        id="shake.amplitude",
        command_path="amplitude",
        syntax_sources=_doc("shake-descriptor"),
        record_type="ShakeDescriptor",
        member_paths=["amplitude"],
        presence_bits=[],
        encoding="curve",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x00788AA0", role="parser")],
        runtime_refs=[],
        notes="+0x08 vector, amplitude values, cShakeAmplitudeCommand::Parse",
    ),
    CommandBinding(
        id="shake.frequency",
        command_path="frequency",
        syntax_sources=_doc("shake-descriptor"),
        record_type="ShakeDescriptor",
        member_paths=["frequency"],
        presence_bits=[],
        encoding="curve",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x00788B30", role="parser")],
        runtime_refs=[],
        notes="+0x14 vector, frequency values, cShakeFrequencyCommand::Parse",
    ),
    CommandBinding(
        id="shake.aspect",
        command_path="aspect",
        syntax_sources=_doc("shake-descriptor"),
        record_type="ShakeDescriptor",
        member_paths=["aspect"],
        presence_bits=[],
        encoding="f32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0077E008", role="parser")],
        runtime_refs=[],
        notes="+0x20, aspect, cShakeAspectCommand::Parse",
    ),
    CommandBinding(
        id="shake.baseTable",
        command_path="baseTable",
        syntax_sources=_doc("shake-descriptor"),
        record_type="ShakeDescriptor",
        member_paths=["base_table"],
        presence_bits=[],
        encoding="enum",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0077E07E", role="parser")],
        runtime_refs=[],
        notes="+0x24, baseTable enum, parsed through executable kShakeBaseTableTypes table, cShakeBaseTableCommand::Parse",
    ),
    CommandBinding(
        id="light.color",
        command_path="color",
        syntax_sources=_doc("light-descriptor"),
        record_type="LightDescriptor",
        member_paths=["color"],
        presence_bits=[],
        encoding="curve",
        transforms=[
            Transform(
                description="parser has an explicit byte-range color scaling path",
                reversible=True,
                implementation="byte_range_scale",
            )
        ],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x00789148", role="parser")],
        runtime_refs=[],
        notes="+0x00 vector, color values, variable-length vector not a fixed-size scalar, cLightColorCommand::Parse",
    ),
    CommandBinding(
        id="light.strength",
        command_path="strength",
        syntax_sources=_doc("light-descriptor"),
        record_type="LightDescriptor",
        member_paths=["strength"],
        presence_bits=[],
        encoding="curve",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x00788C86", role="parser")],
        runtime_refs=[],
        notes="+0x0c vector, strength values, variable-length float curve, cLightStrengthCommand::Parse",
    ),
    CommandBinding(
        id="light.length",
        command_path="length",
        syntax_sources=_doc("light-descriptor"),
        record_type="LightDescriptor",
        member_paths=["length"],
        presence_bits=[],
        encoding="f32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0077DB2A", role="parser")],
        runtime_refs=[],
        notes="+0x18, length, cLightLengthCommand::Parse",
    ),
    CommandBinding(
        id="effect.viewRelative",
        command_path="viewRelative",
        syntax_sources=_doc("effect-records"),
        record_type="EffectDescription",
        member_paths=["flags"],
        presence_bits=[BitRef(member_path="flags", bit=0)],
        encoding="u32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078510A", role="parser")],
        runtime_refs=[],
        notes="bitset bit 0, direct bit set, cGroupEffectCommand::Parse",
    ),
    CommandBinding(
        id="effect.noAutoStop",
        command_path="noAutoStop",
        syntax_sources=_doc("effect-records"),
        record_type="EffectDescription",
        member_paths=["flags"],
        presence_bits=[BitRef(member_path="flags", bit=1)],
        encoding="u32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078510A", role="parser")],
        runtime_refs=[],
        notes="bitset bit 1, direct bit set, cGroupEffectCommand::Parse",
    ),
    CommandBinding(
        id="effect.hardStop",
        command_path="hardStop",
        syntax_sources=_doc("effect-records"),
        record_type="EffectDescription",
        member_paths=["flags"],
        presence_bits=[BitRef(member_path="flags", bit=2)],
        encoding="u32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078510A", role="parser")],
        runtime_refs=[],
        notes="bitset bit 2, direct bit set, cGroupEffectCommand::Parse",
    ),
    CommandBinding(
        id="effect.rigid",
        command_path="rigid",
        syntax_sources=_doc("effect-records"),
        record_type="EffectDescription",
        member_paths=["flags"],
        presence_bits=[BitRef(member_path="flags", bit=3)],
        encoding="u32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078510A", role="parser")],
        runtime_refs=[],
        notes="bitset bit 3, direct bit set, cGroupEffectCommand::Parse",
    ),
    CommandBinding(
        id="effect.noPropagate",
        command_path="noPropagate",
        syntax_sources=_doc("effect-records"),
        record_type="EffectDescription",
        member_paths=["flags"],
        presence_bits=[BitRef(member_path="flags", bit=4)],
        encoding="u32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078510A", role="parser")],
        runtime_refs=[],
        notes="bitset bit 4, direct bit set, cGroupEffectCommand::Parse",
    ),
    CommandBinding(
        id="effect.applyCursor",
        command_path="applyCursor",
        syntax_sources=_doc("effect-records"),
        record_type="EffectDescription",
        member_paths=["flags"],
        presence_bits=[BitRef(member_path="flags", bit=5)],
        encoding="u32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078510A", role="parser")],
        runtime_refs=[],
        notes="bitset bit 5, direct bit set, cGroupEffectCommand::Parse",
    ),
    CommandBinding(
        id="effect.ignoreOrientation",
        command_path="ignoreOrientation",
        syntax_sources=_doc("effect-records"),
        record_type="EffectDescription",
        member_paths=["flags"],
        presence_bits=[BitRef(member_path="flags", bit=6)],
        encoding="u32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078510A", role="parser")],
        runtime_refs=[],
        notes="bitset bit 6, direct bit set, cGroupEffectCommand::Parse",
    ),
    CommandBinding(
        id="effect.noLODStop",
        command_path="noLODStop",
        syntax_sources=_doc("effect-records"),
        record_type="EffectDescription",
        member_paths=["flags"],
        presence_bits=[BitRef(member_path="flags", bit=7)],
        encoding="u32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078510A", role="parser")],
        runtime_refs=[],
        notes="bitset bit 7, direct bit set, cGroupEffectCommand::Parse",
    ),
    CommandBinding(
        id="effect.manualRestart",
        command_path="manualRestart",
        syntax_sources=_doc("effect-records"),
        record_type="EffectDescription",
        member_paths=["flags"],
        presence_bits=[BitRef(member_path="flags", bit=8)],
        encoding="u32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078510A", role="parser")],
        runtime_refs=[],
        notes="bitset bit 8, direct bit set, cGroupEffectCommand::Parse",
    ),
    CommandBinding(
        id="effect.priority",
        command_path="priority",
        syntax_sources=_doc("effect-records"),
        record_type="EffectDescription",
        member_paths=["priority"],
        presence_bits=[],
        encoding="u32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078510A", role="parser")],
        runtime_refs=[],
        notes="+0x04, priority, direct scalar assignment, cGroupEffectCommand::Parse",
    ),
    CommandBinding(
        id="effect.startMessage",
        command_path="startMessage",
        syntax_sources=_doc("effect-records"),
        record_type="EffectDescription",
        member_paths=["events"],
        presence_bits=[],
        encoding="u32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078510A", role="parser")],
        runtime_refs=[],
        notes="+0x20/+0x24/+0x28, startMessage arguments 1-3, direct scalar assignments, cGroupEffectCommand::Parse",
    ),
    CommandBinding(
        id="description.ignoreLength",
        command_path="ignoreLength",
        syntax_sources=_doc("effect-child-records"),
        record_type="DescriptionRecord",
        member_paths=["flags"],
        presence_bits=[BitRef(member_path="flags", bit=0)],
        encoding="u32",
        transforms=[],
        shared_storage_group="description.flags.bit0",
        conflicts=["description.respectLength"],
        evidence="parser",
        parser_refs=[CodeRef(address="0x00401D2C", role="parser")],
        runtime_refs=[],
        notes="+0x08 bit 0; ignoreLength sets it, respectLength clears it, cSC4EffectsParser::ParseDescRecOptions",
    ),
    CommandBinding(
        id="description.offset",
        command_path="offset",
        syntax_sources=_doc("effect-child-records"),
        record_type="DescriptionRecord",
        member_paths=["legacy_transform"],
        presence_bits=[],
        encoding="Vec3",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x00401D2C", role="parser")],
        runtime_refs=[],
        notes="+0x34/+0x38/+0x3c, offset vector components, cSC4EffectsParser::ParseDescRecOptions",
    ),
    CommandBinding(
        id="description.lod",
        command_path="lod",
        syntax_sources=_doc("effect-child-records"),
        record_type="DescriptionRecord",
        member_paths=["lod", "lod_range"],
        presence_bits=[],
        encoding="u8",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x00401D2C", role="parser")],
        runtime_refs=[],
        notes="+0x44/+0x45, lod/lodRange low/high bytes, parser default 1/6, cSC4EffectsParser::ParseDescRecOptions",
    ),
    CommandBinding(
        id="scrubber.demolish",
        command_path="-demolish",
        syntax_sources=_doc("component-records"),
        record_type="ScrubberDescription",
        member_paths=["value_14"],
        presence_bits=[],
        encoding="u32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078BC26", role="parser")],
        runtime_refs=[],
        notes="+0x14, -demolish, cGroupScrubberCommand::Parse",
    ),
    CommandBinding(
        id="scrubber.message",
        command_path="-message",
        syntax_sources=_doc("component-records"),
        record_type="ScrubberDescription",
        member_paths=["message_1", "message_2"],
        presence_bits=[],
        encoding="u32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078BC26", role="parser")],
        runtime_refs=[],
        notes="+0x30/+0x34, -message arguments 1-2, cGroupScrubberCommand::Parse",
    ),
    CommandBinding(
        id="scrubber.minMaxDemolishSize",
        command_path="-minDemolishSize/-maxDemolishSize",
        syntax_sources=_doc("component-records"),
        record_type="ScrubberDescription",
        member_paths=["min_size", "max_size"],
        presence_bits=[],
        encoding="f32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078BC26", role="parser")],
        runtime_refs=[],
        notes="+0x1c/+0x20, -minDemolishSize/-maxDemolishSize, cGroupScrubberCommand::Parse",
    ),
    CommandBinding(
        id="scrubber.action",
        command_path="explode/createRubble/createBurntRubble/demolishEffectID",
        syntax_sources=_doc("component-records"),
        record_type="ScrubberDescription",
        member_paths=["action"],
        presence_bits=[],
        encoding="raw",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078BC26", role="parser")],
        runtime_refs=[],
        notes="+0x18, demolition action/effect packed value; parser combines several source options, exact sub-bit semantics open",
    ),
    CommandBinding(
        id="brush.name",
        command_path="-name",
        syntax_sources=_doc("component-records"),
        record_type="BrushDescription",
        member_paths=["key"],
        presence_bits=[],
        encoding="resource_key",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078C690", role="parser")],
        runtime_refs=[],
        notes="+0x0c, -name resource key, cGroupBrushCommand::Parse",
    ),
    CommandBinding(
        id="brush.rate",
        command_path="-rate",
        syntax_sources=_doc("component-records"),
        record_type="BrushDescription",
        member_paths=["rate"],
        presence_bits=[],
        encoding="f32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078C690", role="parser")],
        runtime_refs=[],
        notes="+0x10, -rate; also -apply value, cGroupBrushCommand::Parse",
    ),
    CommandBinding(
        id="brush.width",
        command_path="-width",
        syntax_sources=_doc("component-records"),
        record_type="BrushDescription",
        member_paths=["width"],
        presence_bits=[],
        encoding="range",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078C690", role="parser")],
        runtime_refs=[],
        notes="+0x28/+0x2c, -width minimum/maximum, cGroupBrushCommand::Parse",
    ),
    CommandBinding(
        id="camera.attachRadius",
        command_path="attachRadius",
        syntax_sources=_doc("component-records"),
        record_type="CameraDescription",
        member_paths=["attach_radius"],
        presence_bits=[],
        encoding="f32",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078B6B8", role="parser")],
        runtime_refs=[],
        notes="+0x14, attachRadius, cGroupCameraCommand::Parse",
    ),
    CommandBinding(
        id="sound.name",
        command_path="-name",
        syntax_sources=_doc("component-records"),
        record_type="SoundDescription",
        member_paths=["resource_key"],
        presence_bits=[],
        encoding="resource_key",
        transforms=[],
        shared_storage_group=None,
        conflicts=[],
        evidence="parser",
        parser_refs=[CodeRef(address="0x0078CC8A", role="parser")],
        runtime_refs=[],
        notes="+0x10, -name resource key, cGroupSoundCommand::Parse",
    ),
]


def find_bindings(record_type: str, member_path: str) -> List[CommandBinding]:
    return [
        binding
        for binding in CATALOG
        if binding.record_type == record_type and member_path in binding.member_paths
    ]


def find_by_id(binding_id: str) -> Optional[CommandBinding]:
    for binding in CATALOG:
        if binding.id == binding_id:
            return binding
    return None
