"""Layer 2: bounded cursor and stream primitives (u8/u16/u32/f32, string,
vector<T>) recovered from the SC4 executable.

This layer knows nothing about DBPF (layer 1) or record/command semantics
(layer 3). See docs/reference/binary/effdir-editor-spec.md, "Three layers".
"""

from .cursor import CursorError, ReadCursor, SourceSpan, WriteCursor
from .preservation import Diagnostic, PreservationData, RawValue, RecordPreservation
from .strings import (
    StringFraming,
    WireString,
    decode_string_length,
    encode_string_length,
    read_wire_string,
    write_wire_string,
)
from .types import (
    Bounds2,
    Bounds3,
    Raw,
    Vec2,
    Vec3,
    make_raw_bitset,
    make_raw_f32,
    make_raw_u8,
    make_raw_u16,
    make_raw_u32,
    read_bitset,
    read_bounds2,
    read_bounds3,
    read_f32,
    read_u8,
    read_u16,
    read_u32,
    read_vec2,
    read_vec3,
    write_bounds2,
    write_bounds3,
    write_raw,
    write_vec2,
    write_vec3,
)
from .vectors import (
    DEFAULT_VECTOR_HARD_LIMIT,
    OptionalVector,
    WireVector,
    empty_vector,
    read_optional_vector,
    read_vector,
    write_optional_vector,
    write_vector,
)

__all__ = [
    "CursorError",
    "ReadCursor",
    "SourceSpan",
    "WriteCursor",
    "Diagnostic",
    "PreservationData",
    "RawValue",
    "RecordPreservation",
    "StringFraming",
    "WireString",
    "decode_string_length",
    "encode_string_length",
    "read_wire_string",
    "write_wire_string",
    "Bounds2",
    "Bounds3",
    "Raw",
    "Vec2",
    "Vec3",
    "make_raw_bitset",
    "make_raw_f32",
    "make_raw_u8",
    "make_raw_u16",
    "make_raw_u32",
    "read_bitset",
    "read_bounds2",
    "read_bounds3",
    "read_f32",
    "read_u8",
    "read_u16",
    "read_u32",
    "read_vec2",
    "read_vec3",
    "write_bounds2",
    "write_bounds3",
    "write_raw",
    "write_vec2",
    "write_vec3",
    "DEFAULT_VECTOR_HARD_LIMIT",
    "OptionalVector",
    "WireVector",
    "empty_vector",
    "read_optional_vector",
    "read_vector",
    "write_optional_vector",
    "write_vector",
]
